"""add payment_method to sales

Revision ID: 43c99803491d
Revises: 68dd97358d36
Create Date: 2026-03-29 18:04:47.681310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c99803491d'
down_revision: Union[str, Sequence[str], None] = '68dd97358d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    
    # Step 1: add column allowing nulls
    op.add_column(
        'sales',
        sa.Column('payment_method', sa.String(), nullable=True)
    )

    # Step 2: update existing rows
    op.execute(
        "UPDATE sales SET payment_method='cash' WHERE payment_method IS NULL"
    )

    # Step 3: enforce NOT NULL
    op.alter_column(
        'sales',
        'payment_method',
        existing_type=sa.String(),
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'payment_method')
    # ### end Alembic commands ###
