"""initial tables

Revision ID: 68dd97358d36
Revises: 
Create Date: 2026-03-29 13:13:57.807072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68dd97358d36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transfers',
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('from_branch', sa.Integer(), nullable=True),
    sa.Column('to_branch', sa.Integer(), nullable=True),
    sa.Column('transfer_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_branch'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['to_branch'], ['branches.branch_id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_table('branch_inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('inventory_id'),
    sa.UniqueConstraint('branch_id', 'product_id', name='uix_branch_product')
    )
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['user_id'])
    op.add_column('branches', sa.Column('name', sa.String(), nullable=False))
    op.create_index(op.f('ix_branches_branch_id'), 'branches', ['branch_id'], unique=False)
    op.drop_column('branches', 'branch_name')
    op.add_column('categories', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.add_column('inventory_movements', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.alter_column('inventory_movements', 'movement_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('inventory_movements', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_inventory_product'), table_name='inventory_movements')
    op.create_index(op.f('ix_inventory_movements_movement_date'), 'inventory_movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_id'), 'inventory_movements', ['movement_id'], unique=False)
    op.create_foreign_key(None, 'inventory_movements', 'branches', ['branch_id'], ['branch_id'])
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_constraint(op.f('payments_sale_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'sales', ['sale_id'], ['sale_id'])
    op.drop_column('payments', 'payment_date')
    op.alter_column('products', 'cost_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('products', 'selling_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_index(op.f('idx_products_barcode'), table_name='products')
    op.drop_constraint(op.f('products_barcode_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.drop_column('products', 'stock_quantity')
    op.drop_column('products', 'reorder_level')
    op.add_column('purchase_orders', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_order_date'), 'purchase_orders', ['order_date'], unique=False)
    op.create_foreign_key(None, 'purchase_orders', 'branches', ['branch_id'], ['branch_id'])
    op.add_column('refunds', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('sale_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sale_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('sale_items', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.create_index(op.f('ix_sale_items_sale_item_id'), 'sale_items', ['sale_item_id'], unique=False)
    op.drop_constraint(op.f('sale_items_sale_id_fkey'), 'sale_items', type_='foreignkey')
    op.create_foreign_key(None, 'sale_items', 'sales', ['sale_id'], ['sale_id'])
    op.add_column('sales', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.alter_column('sales', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_index(op.f('idx_sales_date'), table_name='sales')
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_sale_id'), 'sales', ['sale_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'branches', ['branch_id'], ['branch_id'])
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['customer_id'])
    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['branch_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'branch_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_sale_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.create_index(op.f('idx_sales_date'), 'sales', ['sale_date'], unique=False)
    op.alter_column('sales', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_column('sales', 'branch_id')
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.create_foreign_key(op.f('sale_items_sale_id_fkey'), 'sale_items', 'sales', ['sale_id'], ['sale_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_sale_items_sale_item_id'), table_name='sale_items')
    op.alter_column('sale_items', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('sale_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('sale_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('refunds', 'amount')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_order_date'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'branch_id')
    op.add_column('products', sa.Column('reorder_level', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('stock_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_unique_constraint(op.f('products_barcode_key'), 'products', ['barcode'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_products_barcode'), 'products', ['barcode'], unique=False)
    op.alter_column('products', 'selling_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('products', 'cost_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.add_column('payments', sa.Column('payment_date', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_sale_id_fkey'), 'payments', 'sales', ['sale_id'], ['sale_id'], ondelete='CASCADE')
    op.alter_column('payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_constraint(None, 'inventory_movements', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_movements_movement_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_date'), table_name='inventory_movements')
    op.create_index(op.f('idx_inventory_product'), 'inventory_movements', ['product_id'], unique=False)
    op.alter_column('inventory_movements', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory_movements', 'movement_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('inventory_movements', 'branch_id')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.drop_column('categories', 'created_at')
    op.add_column('branches', sa.Column('branch_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_branches_branch_id'), table_name='branches')
    op.drop_column('branches', 'name')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_table('branch_inventory')
    op.drop_table('stock_transfers')
    # ### end Alembic commands ###
